//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _619_Gorlanov_KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilion
    {
        public int ID { get; set; }
        public int ShoppingCenterID { get; set; }
        public string PavilionNumber { get; set; }
        public int Floor { get; set; }
        public int StatusPavilionID { get; set; }
        public double Square { get; set; }
        public double PricePerSquare { get; set; }
        public double ValueAddedRatio { get; set; }
    
        public virtual ShoppingCenter ShoppingCenter { get; set; }
        public virtual StatusPavilion StatusPavilion { get; set; }
    }
}
