//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_Gorlanov_619
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturerCarModel
    {
        public int ID { get; set; }
        public int CarModelID { get; set; }
        public int ManufacturerID { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
